language: csharp
solution: MonoTest.sln
install:
  - nuget restore MonoTest.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release MonoTest.sln
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./MonoTest.Tests/bin/Release/MonoTest.Tests.dll
