language: csharp

solution: MonoTest.sln

install:
  - nuget restore MonoTest.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release MonoTest.sln
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./MonoTest.Tests/bin/Release/MonoTest.Tests.dll -noappdomain

before_deploy:
  - export DATE=`date +%Y-%m-%d`
  - mkdir "deploy"
  - mv MonoTest/bin/Release/* build/MonoTest
  - tar -zcvf deploy/MonoTest-$DATE-$TRAVIS_COMMIT.tar.gz build/* || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: deploy
    bucket: monotest-deploy
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    region: us-west-2
    on:
      repo: zorbfish/monotest
      all_branches: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: monotest-deploy
    key: MonoTest-$DATE-$TRAVIS_COMMIT.tar.gz
    bundle_type: tgz 
    application: MonoTest
    deployment_group: MonoTest
    region: us-west-2
    on:
      repo: zorbfish/monotest
      all_branches: true
